name: MacDerleme
on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Python Yukle
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Yuklemeler
        run: |
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Derleme Basliyor
        run: pyinstaller --onefile --windowed main.py

      - name: Sonucu Kaydet
        uses: actions/upload-artifact@v3
        with:
          name: MacUygulamasi
          path: dist/
